### ISSUE TITLE
missing version metadata

### ISSUE THREAD

**Issue by bstarynk** [devkitPro/libogc#102]
(I never used your library, but I did answer to some question about it, with a suggestion for you)

Regards.

Basile Starynkevitch <basile@starynkevitch.net>
92340 Bourg La Reine, France

**Comment by WinterMute** [comment]
Use of old library versions is discouraged. Attempts to support multiple versions of old libraries are unsupported.

Ultimately it's better for homebrew to be updated to work with latest tools and libraries than to attempt to continue to use old unsupported versions. We work with game consoles that don't have full public documentation and attempt to make these as accessible as we can to amateur programmers. This often means that tools and libraries must be updated to fix bugs, false assumptions and incomplete knowledge and that people not only using unsupported tools and libraries but actively encouraging their use instead of updating projects to work with the latest iterations are actively harming the homebrew community.
