### ISSUE TITLE
Error when compiling with strict error reporting

### ISSUE THREAD

**Issue by techflashYT** [devkitPro/libogc#128]
When compiling with very strict error reporting settings in GCC (I like my code to be squeaky clean), the compiler gives me this error:
```
/opt/devkitpro/libogc/include/ogc/es.h:150:21: error: ISO C++ forbids flexible array member 'contents' [-Werror=pedantic]
  150 |         tmd_content contents[];
      |                     ^~~~~~~~
/opt/devkitpro/libogc/include/ogc/es.h:172:26: error: ISO C++ forbids flexible array member 'contents' [-Werror=pedantic]
  172 |         tmd_view_content contents[]; //0x005c
      |                          ^~~~~~~~
cc1plus: all warnings being treated as errors
make[1]: *** [/opt/devkitpro/devkitPPC/base_rules:13: init.o] Error 1
make: *** [Makefile:98: build] Error 2
```
My CFLAGS line:
`-Ofast -Wall -Wextra -Wformat-truncation -Wformat-overflow -Wpedantic -Wshadow -Wformat=2 -Wconversion -Wunused-parameter -fsanitize=address,undefined -Werror $(MACHDEP) $(INCLUDE)`
Is this fixable?  Or do I just need to turn off `-Wpedantic`?
EDIT:  And no, wrapping the includes in an `extern "C"` didn't help either.

**Comment by DacoTaco** [comment]
im no expert, but the problem here is that the content array has no fixed length and changes between titles (as some titles have more content files than others) and this is C code, not C++ (so no access to std::vector, which in turn would increase code size too).

the only thing i can think of is to make this a pointer?
maybe @WinterMute knows something?

**Comment by endrift** [comment]
You can't do this with a pointer. A flexible array is effectively syntactic sugar for the memory past the end of the struct. Generally I don't recommend using them since their memory semantics are, well, weird (which is probably why C++ disallows them), but it's impossible to solve this in a way that placates both the C++ compiler and preserves backwards compatibility. You should probably just turn off `-Wpedantic`, to be honest, since at this point I think changing that API is unlikely to happen.

**Comment by DacoTaco** [comment]
ye, thats fair. changing the API would sadly break to much stuff. and if a pointer to replace the array won't work, then i also think turning off the warning is best.

**Comment by techflashYT** [comment]
Alright, I guess I'll just use pragmas to disable it temporarily for that include, even though it's a pain, that's still a better option than breaking backwards compatibility or just disabling the warning altogether, potentially breaking some of my code...
