### ISSUE TITLE
[request] high-level SHA function

### ISSUE THREAD

**Issue by pyorot** [devkitPro/libogc#185]
## Feature Request

A continuation of a conversation with @DacoTaco.

#### Overview:
It'd be nice to have a `SHA` function with a similar API as the one that's been [passed around for years](https://github.com/systemwii/monke/blob/main/sha1/sha1.h) in homebrew projects. It manages its own memory and just hashes data at `*ptr` of size `size`, writing the result to a u8[20] buffer `*outbuf`.

#### Smaller Details:
It'd be nice to have this function open a connection with IOS if one isn't open yet, just-in-time. But a requiring a second SHA call to init the SHA device isn't so bad. Input data having to be 64-byte aligned is an unfortunate downgrade (beware btw: source code says 64-bit), but only slightly inconvenient.

#### Nature of Request:  
- Addition

### Why would this feature be useful?
All things considered, this API would make for a good change to most projects in simplifying their code and cutting down on modules, whereas currently, IOS SHA can't be used without complicating code, so the traditional module I linked above wins the cost/benefit.

**Comment by DacoTaco** [comment]
ha, thanks for reminding me of this chat we had haha.

like i said, i think the `SHA_Init` should still be called by the application so the developer knows that the sha interface has been opened so that, if they were to do some ios reloading, they need to close it as well.

however, i do think the function itself (which allocates a context, uses it, and frees it again) is a nice one if it will replace all that copy pasting of the sha functions that have happened over the years (and i have been guilty of too with priiloader...)

**Comment by DacoTaco** [comment]
the `SHA_Calculate` function has been made to implement this.
if a manual SHA1 calculation is required, the `SHA_InitialiseContext`, `SHA_Input`and `SHA_Finalize` functions can be used.
